######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 14:23:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += MainWindow.hpp
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp MainWindow_funcs.cpp
